# DualClock Configuration
# Place this file at /etc/world-clock/clock.conf
#
# Timezone values must be valid IANA timezone strings.
# See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Left Clock Settings
TIMEZONE_LEFT = "Asia/Karachi"
LOCATION_LEFT = "اسلام آباد"

# Right Clock Settings
TIMEZONE_RIGHT = "Asia/Riyadh"
LOCATION_RIGHT = "مكة المكرمة"
